### ISSUE TITLE
Reinsert all assertions dealing with not visiting bottom

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#13]
(after BBs belonging to (currently) not reachable nodes are no longer added to worklist)

**Comment by michael-schwarz** [comment]
https://github.com/peterrum/po-lab-2018/commit/b47de7946dabb6816696c72ccea50dd64acec27a does not completely solve the issue yet, we also need to be smart in the beginning (e.g. putting only first basic block of each function) before we can reinsert the assertions

**Comment by peterrum** [comment]
Putting only first basic block of each function to worklist has been implemented in commit 37c0e3a . Assert have been reinserted in commit 44e79c3 and do not seem to cause any problems.

**Comment by peterrum** [comment]
Only process one (non-empty) function at a time has been implemented in the commits 171d450 and b3c9f1f.
