### ISSUE TITLE
Deal with comparisons involving two vars

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#14]
They should limit the values of both involved vars

**Comment by michael-schwarz** [comment]
be careful to not carry around consts in conditons

**Comment by peterrum** [comment]
see: samples/cmp-two-variables-1.c and samples/cmp-two-variables-2.c

**Comment by michael-schwarz** [comment]
Wow, burning the midnight oil? Good job!

Reopening because this does not correctly deal with comparisons of two variables yet:
X < Y should constrain both x and y in both branches, but state right now can only deal with path conditions for one variable. We need to replace pair<value,Ad> with a map in the branch conditions to do this.

**Comment by peterrum** [comment]
Change from pair to map has been implemented  in commit 369d907. Implementation has to be checked.

**Comment by michael-schwarz** [comment]
Looks good at first glance, will try to write a couple test programs and look for edge cases tonight, but not sure if I'll have time....
Otherwise I'll do that during the talk on Monday (I only give the last part, first is Schnittstelle- Hochschule-Schule for 45mins)
