### ISSUE TITLE
Prune implementation is incorrect

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#17]
If on first visit to a BB there are vars present because of phi nodes they will remain in state forever.
When fixing this it might also be nice to refactor this to be more obvious than our current implementation

**Comment by peterrum** [comment]
Please elaborate!

**Comment by michael-schwarz** [comment]
See samples/if-then-else-2.c

**IS**
VsaVisitor::print():if.end
call -> T
add -> {49}

**SHOULD BE**
call -> T
add -> T

or better yet: add not present.
