### ISSUE TITLE
Separate state and branch conditions

### ISSUE THREAD

**Issue by peterrum** [peterrum/po-lab-2018#19]
BasicBlockWrapper is responsible for one BB and has a state and branch conditions.

**Comment by michael-schwarz** [comment]
How will this improve quality?
The branch conditions will always have to be applied to the state to get the correct incoming state for successors, so I don't see why it is a good idea to separate them yet.
Is there something I'm missing?

**Comment by peterrum** [comment]
Done in commit 7244b91.
