### ISSUE TITLE
LUB  is incorrect

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#20]
LUB({x->49},{x->49}) = {x->T}
caused by either wrong LUB in state or in BoundedSet

See if-then-else.c

**IS**
VsaVisitor::print():entry
add -> {49}
call -> T
VsaVisitor::print():if.then
add -> {49}
call -> T
VsaVisitor::print():if.end
add -> T
call -> T

**SHOULD BE**
VsaVisitor::print():entry
add -> {49}
call -> T
VsaVisitor::print():if.then
add -> {49}
call -> T
VsaVisitor::print():if.end
add -> {49}
call -> T

**Comment by peterrum** [comment]
The problem are the branch conditions of the else branch. Its result is add->T.

**Comment by jerhard** [comment]
Fixed in commit b3431ae0bf227f456833d88961d939e7b21eec5f.
