### ISSUE TITLE
Compare quality of results with LazyValueInfo

### ISSUE THREAD

**Issue by peterrum** [peterrum/po-lab-2018#38]

**Comment by peterrum** [comment]
Started in commit b00244e.

**Comment by peterrum** [comment]
Has been integrated into tutorial. TODO: evaluate for corner cases and strided intervals!

**Comment by michael-schwarz** [comment]
Is this correctly implemented?

See ./run_tutorial.sh switch.c
```
VSA: add T
LVI: add T

AD getNumValues: '3'
AD getValue: '8'
AD getValue: '10'
AD getValue: '17'
AD UMin: '8'
AD SMin: '8'
AD UMax: '17'
AD SMax: '17'
----------------------------------
```

**Comment by michael-schwarz** [comment]
It is correct, it is the result of comparing it to the constant 12(?), changing output to be more obvious

**Comment by michael-schwarz** [comment]
also use LVI.getConstantRange()
