### ISSUE TITLE
Strided Interval contains fails at line 348 with APInt assertion

### ISSUE THREAD

**Issue by arosch** [peterrum/po-lab-2018#42]
RHS.U.VAL != 0 && Remainder by zero? failed

**Comment by jagottf** [comment]
The same problem will occur 9 lines above. We first need to check, if it is a singleton interval.

**Comment by peterrum** [comment]
I have fixed the problem and have filled functionalities in StridedIntervals in a couple of commit today. For simple test examples comparisons with eq, ne, le and ge is working. The code has to be checked and refactored. For this purpose I create a new issue and close this one.
