### ISSUE TITLE
StridedIntervals: check added code and fill in remaining functions

### ISSUE THREAD

**Issue by peterrum** [peterrum/po-lab-2018#45]

**Comment by peterrum** [comment]
Fix strides in comparison...

**Comment by jagottf** [comment]
> Fix strides in comparison...

Please elaborate.

**Comment by jerhard** [comment]
The implementation of icmp in StridedIntervals now uses an intersect function of two StridedIntervals. 
This intersect function currently over-approximates the intersection, and uses a stride of one (1) in the resulting StridedInterval. 
To become more precise, we would have to find the first element that is contained in both StridedIntervals (if any), and set the stride to the least common multiple of the strides of both intervals.
