### ISSUE TITLE
size() in StridedInterval is wrong (off-by-1)

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#50]
**SHOUD BE**
size(1[0,1]_32) = 2

**IS**
size(1[0,1]_32) = 1

**SUGGESTED FIX**
Add 1 to end in StridedInterval.cpp:594
This however breaks behavior in a ton of other places (e.g. negative strides) in the StridedIntervals, so leaving this to @jagottf

**Comment by jagottf** [comment]
You are right. `size` was implemented in a hurry.

**Comment by jagottf** [comment]
Is this solved by 0c28f3544759e63c132c5953aacc174859941dc7?

**Comment by michael-schwarz** [comment]
Yes, it is!
