### ISSUE TITLE
Implement trivial widening for strided intervals

### ISSUE THREAD

**Issue by arosch** [peterrum/po-lab-2018#56]

**Comment by michael-schwarz** [comment]
After fixed number of update operations, put variable state to T to ensure termination.

This is implicit in the upper bound on #elements in set.

**Comment by michael-schwarz** [comment]
Works and ensures termination by going to T after WIDENING_AFTER changes (see util.h), if the abstract domain requires widening, still needs to be implemented for CompositeDomain (delegate to current representation for this value).

Also I will see if we can be at least a bit smarter and try to preserve stride information when performing widening at first
widen(s[x,y]) = s[MIN_INT,MAX_INT]
widen(s[MIN_INT,MAX_INT]) = T (i.e. 1[MIN_INT,MAX_INT])

**Comment by michael-schwarz** [comment]
On second thought,
`!(s[x,y]  <= s[MIN_INT,MAX_INT])` because that would shift the begin. So we can't do that.
Will stick with naive variant for now

**Comment by michael-schwarz** [comment]
As this problem was addressed by the new course this term, solving this here is no longer necessary.
