### ISSUE TITLE
sdiv is currently not sound

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#59]
Always returns bottom. I guess you rely on this behavior somewhere else @jagottf ?

Definitely need to fix this by either implementing sdiv or returning T if we don't have the time to do it.

Can be tested with ops.c

**Comment by jagottf** [comment]
I don’t rely on it, It’s just the only function I forgot to change. Feel free to copy the code from one of the other unimplemented instructions below. Otherwise I will fix it tomorrow.

**Comment by jagottf** [comment]
Fixed by 09f601d63493110c8339f963ea5074b7feecf3ad.
