### ISSUE TITLE
Abstract Interpretation Functions

### ISSUE THREAD

**Issue by DrMichaelPetter** [peterrum/po-lab-2018#7]
Start implementing functions for interpreting LLVM-IR statements on lifted VSAs (states)
a) for clarifying the needs wrt. the fixpoint infrastructure (e.g. access to src/tgt states, information about #registers, aso.)
b) for clarifying the needs wrt. the abstract domain interface (e.g. creating new mappings register->VS, computing with states, aso.)

**Comment by michael-schwarz** [comment]
Implemented as of Friday:

- phi
- add
- mul
- br

- TerminatorInst
